import { Property, Locality, BlogArticle, Service } from './types';

export const mockProperties: Property[] = [
  {
    id: '1',
    slug: 'casa-spatiosa-teren-straseni',
    title: 'Casă spațioasă cu teren în Strășeni',
    type: 'casa',
    locality: 'Strășeni',
    address: 'Strada Principale nr. 42, Strășeni',
    price: 68000,
    priceLabel: '68.000 EUR',
    area: 220,
    rooms: 5,
    landArea: 1200,
    image: 'https://images.unsplash.com/photo-1570129477492-45c003d96918?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003d96918?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&h=750&fit=crop',
    ],
    description: 'Casă confortabilă cu 5 camere, situată pe terenul propriu de 12 ari. Dispune de grădină frumoasă, acces la drum principal, apă curentă, canalizare și curent electric.',
    amenities: ['Bucătărie modernă', 'Baie completă', 'Salon spațios', 'Grădină', 'Garaj'],
    utilities: [
      { name: 'Apă curentă', available: true },
      { name: 'Curent electric', available: true },
      { name: 'Canalizare', available: true },
      { name: 'Gaz', available: false },
    ],
    year: 1998,
    condition: 'Bună',
    heating: 'Șemineu și încălzire electrică',
    roadAccess: 'Drum asfaltat',
    featured: true,
    badge: 'Recomandat',
    contact: {
      name: 'Ion Popescu',
      phone: '+373 69 123 456',
    },
  },
  {
    id: '2',
    slug: 'apartament-2-camere-centru-straseni',
    title: 'Apartament cu 2 camere în centrul Strășeniului',
    type: 'apartament',
    locality: 'Strășeni',
    address: 'Strada Teatrului nr. 15, Strășeni',
    price: 35000,
    priceLabel: '35.000 EUR',
    area: 52,
    rooms: 2,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1512207736139-0b1fd6806aa7?w=1000&h=750&fit=crop',
    ],
    description: 'Apartament confortabil cu 2 camere într-o clădire consolidată din centrul orașului. Etaj intermediar, pereți interiori, acces ușor la magazine și servicii.',
    amenities: ['Bucătănie', 'Baie', 'Balcon', 'Debara'],
    utilities: [
      { name: 'Apă curentă', available: true },
      { name: 'Curent electric', available: true },
      { name: 'Canalizare', available: true },
      { name: 'Gaz', available: true },
    ],
    year: 2005,
    condition: 'Bună',
    heating: 'Centralizat',
    featured: true,
    badge: 'Nou',
    contact: {
      name: 'Ana Vasilescu',
      phone: '+373 69 234 567',
    },
    sold: true,
  },
  {
    id: '3',
    slug: 'teren-constructii-cojusna',
    title: 'Teren pentru construcții în Cojușna',
    type: 'teren',
    locality: 'Cojușna',
    address: 'Drumul hacia Chișinău, Cojușna',
    price: 12000,
    priceLabel: '12.000 EUR',
    area: 1500,
    landArea: 1500,
    image: 'https://images.unsplash.com/photo-1500595046743-05271c48d7d7?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1500595046743-05271c48d7d7?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&h=750&fit=crop',
    ],
    description: 'Teren ideologic poziționat pentru construcții cu acces la drum asfaltat. Terenul este plan, deschis și ușor de lucrat. Acces la toate utilităților din proximitate.',
    amenities: ['Acces la drum asfaltat', 'Teren plan'],
    utilities: [
      { name: 'Curent electric', available: true },
      { name: 'Apă curentă', available: false },
      { name: 'Gaz', available: false },
    ],
    condition: 'Arabil',
    roadAccess: 'Drum asfaltat',
    featured: true,
    badge: 'Promovat',
    contact: {
      name: 'Gheorghe Nicu',
      phone: '+373 69 345 678',
    },
  },
  {
    id: '4',
    slug: 'casa-renovata-sireti',
    title: 'Casă renovată în Sireți',
    type: 'casa',
    locality: 'Sireți',
    address: 'Sireți, Raionul Strășeni',
    price: 52000,
    priceLabel: '52.000 EUR',
    area: 180,
    rooms: 4,
    landArea: 800,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&h=750&fit=crop',
    ],
    description: 'Casă renovată recent cu 4 camere, situată lângă Chișinău. Renovări de calitate, sobă pe lemn, grădină cu fructiferi.',
    amenities: ['Bucătărie modernă', 'Baie', 'Salon', 'Grădină cu fructiferi', 'Crama'],
    utilities: [
      { name: 'Apă curentă', available: true },
      { name: 'Curent electric', available: true },
      { name: 'Canalizare', available: true },
    ],
    year: 1985,
    condition: 'Renovată',
    heating: 'Sobă pe lemn și curent electric',
    featured: false,
    contact: {
      name: 'Maria Cristescu',
      phone: '+373 69 456 789',
    },
  },
  {
    id: '5',
    slug: 'teren-agricol-lozova',
    title: 'Teren agricol în Lozova',
    type: 'teren',
    locality: 'Lozova',
    address: 'Lozova, Raionul Strășeni',
    price: 8000,
    priceLabel: '8.000 EUR',
    area: 5000,
    landArea: 5000,
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad576?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&h=750&fit=crop',
    ],
    description: 'Teren agricol de 50 ari în Lozova, acces la drum. Solul este fertil și se poate cultiva o varietate de culturi.',
    amenities: ['Acces la drum', 'Sol fertil'],
    utilities: [
      { name: 'Curent electric', available: false },
      { name: 'Apă curentă', available: false },
    ],
    condition: 'Agricol',
    roadAccess: 'Drum de pământ',
    featured: false,
    contact: {
      name: 'Petru Rusnac',
      phone: '+373 69 567 890',
    },
  },
  {
    id: '6',
    slug: 'spatiu-comercial-straseni',
    title: 'Spațiu comercial în Strășeni',
    type: 'comercial',
    locality: 'Strășeni',
    address: 'Strada Principale nr. 28, Strășeni',
    price: 45000,
    priceLabel: '45.000 EUR',
    area: 85,
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1000&h=750&fit=crop',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1000&h=750&fit=crop',
    ],
    description: 'Spațiu comercial modern, parter, cu acces direct de pe strada principală. Ideal pentru magazine, birou sau servicii.',
    amenities: ['Acces principal', 'Parter', 'Geamuri mari', 'Baie'],
    utilities: [
      { name: 'Apă curentă', available: true },
      { name: 'Curent electric', available: true },
      { name: 'Gaz', available: true },
    ],
    year: 2010,
    condition: 'Bună',
    featured: true,
    contact: {
      name: 'Mircea Șovelea',
      phone: '+373 69 678 901',
    },
  },
];

export const mockLocalities: Locality[] = [
  {
    slug: 'straseni',
    name: 'Strășeni',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=600&fit=crop',
    description: 'Municipiu cu o comună bogată de istorie și cultură. Ideal pentru locuințe la mica distanță de Chișinău.',
    listingsCount: 24,
    distance: '~40 km de Chișinău',
    advantages: [
      'Aproape de Chișinău',
      'Infrastructură dezvoltată',
      'Viață de comună frumoasă',
      'Prețuri accesibile',
    ],
    disadvantages: [
      'Transportul public limitat',
      'Serviciile medicale sunt la Chișinău',
    ],
    indicativePrices: {
      houses: '50.000 - 80.000 EUR',
      apartments: '30.000 - 50.000 EUR',
      land: '8.000 - 15.000 EUR pe ari',
    },
  },
  {
    slug: 'cojusna',
    name: 'Cojușna',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    description: 'Sat frumos din raionul Strășeni, cu tradiții locale și o comunitate prietenoasă.',
    listingsCount: 8,
    distance: '~50 km de Chișinău',
    advantages: ['Liniștit și sigur', 'Acces ușor la Chișinău', 'Comunitate frumoasă'],
    disadvantages: ['Servicii limitate', 'Transportul public mic'],
    indicativePrices: {
      houses: '40.000 - 60.000 EUR',
      land: '6.000 - 10.000 EUR pe ari',
    },
  },
  {
    slug: 'sireti',
    name: 'Sireți',
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&h=600&fit=crop',
    description: 'Sat din proximitatea Chișinăului cu acces bun la capitală.',
    listingsCount: 6,
    distance: '~30 km de Chișinău',
    advantages: ['Foarte aproape de Chișinău', 'Locuință liniștită', 'Prețuri bune'],
    disadvantages: ['Infrastructură în dezvoltare'],
    indicativePrices: {
      houses: '45.000 - 65.000 EUR',
      land: '10.000 - 16.000 EUR pe ari',
    },
  },
  {
    slug: 'vatra',
    name: 'Vatra',
    image: 'https://images.unsplash.com/photo-1469022563149-aa64dbd37dae?w=800&h=600&fit=crop',
    description: 'Sat liniștit cu tradițional și natură frumoasă.',
    listingsCount: 4,
    distance: '~45 km de Chișinău',
    advantages: ['Natural și liniștit', 'Aproape de Chișinău', 'Comunitate primească'],
    indicativePrices: {
      houses: '35.000 - 55.000 EUR',
      land: '5.000 - 9.000 EUR pe ari',
    },
  },
  {
    slug: 'lozova',
    name: 'Lozova',
    image: 'https://images.unsplash.com/photo-1489424731066-81342ee5ff30?w=800&h=600&fit=crop',
    description: 'Sat agricol cu terenuri fertile și acces bun.',
    listingsCount: 5,
    distance: '~55 km de Chișinău',
    advantages: ['Terenuri fertile', 'Prețuri foarte bune', 'Ideal pentru agricultură'],
    disadvantages: ['Ceva mai departe de Chișinău'],
    indicativePrices: {
      houses: '30.000 - 45.000 EUR',
      land: '4.000 - 7.000 EUR pe ari',
    },
  },
  {
    slug: 'capriana',
    name: 'Căpriana',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
    description: 'Sat istoric cu mnăstire și peisaj natural frumos.',
    listingsCount: 3,
    distance: '~50 km de Chișinău',
    advantages: ['Istoric și atractiv', 'Peisaj frumos', 'Liniștit'],
    indicativePrices: {
      houses: '40.000 - 60.000 EUR',
      land: '8.000 - 12.000 EUR pe ari',
    },
  },
];

export const mockArticles: BlogArticle[] = [
  {
    id: '1',
    slug: 'cat-costa-apartament-straseni',
    title: 'Cât costă un apartament în Strășeni? Prețuri 2026',
    excerpt: 'Analiză detaliată a prețurilor apartamentelor în Strășeni, comparații cu alte regiuni și sfaturi pentru cumpărători.',
    content: 'Apartamentele din Strășeni au prețuri foarte accesibile, cu o medie de 35.000 - 50.000 EUR pentru o locuință cu 2-3 camere. Raionul Strășeni oferă cea mai bună relație preț-calitate pentru cei care lucrează în Chișinău.',
    category: 'Piața imobiliară',
    author: 'Andrei Moldovanu',
    date: '2026-07-28',
    readingTime: 8,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    tags: ['apartamente', 'prețuri', 'Strășeni', 'imobiliare'],
  },
  {
    id: '2',
    slug: 'merita-cumpara-casa-straseni',
    title: 'Merită să cumperi o casă în Strășeni? Ghid complet 2026',
    excerpt: 'Argumentele pro și contra pentru a investi în proprietăți imobiliare în municipiul Strășeni.',
    content: 'Pentru mulți oameni care lucrează în Chișinău dar doresc o viață mai liniștită, Strășeni este o alegere perfectă. Acest ghid vă va ajuta să luați decizia corectă.',
    category: 'Ghid pentru cumpărători',
    author: 'Elena Popescu',
    date: '2026-07-20',
    readingTime: 10,
    image: 'https://images.unsplash.com/photo-1570129477492-45c003d96918?w=800&h=600&fit=crop',
    tags: ['case', 'investiție', 'Strășeni', 'cumpărare'],
  },
  {
    id: '3',
    slug: 'cum-verifica-actele-teren',
    title: 'Cum verifici actele unui teren? Ghid complet',
    excerpt: 'Ghid complet pentru verificarea documentației legale și cadei unui teren înainte de cumpărare.',
    content: 'Înainte de a cumpăra un teren, este esențial să verifici mai mulți documente importante. Documentele care trebuie verificate includ: certificatul de proprietate, planul cadastral, certificatul de neîncărcare.',
    category: 'Acte și verificări',
    author: 'Cristian Nicu',
    date: '2026-07-15',
    readingTime: 12,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    tags: ['teren', 'documente', 'verificare', 'acte'],
  },
  {
    id: '4',
    slug: 'cele-mai-bune-localitati-langa-chisinau',
    title: 'Cele mai bune localități pentru o casă lângă Chișinău',
    excerpt: 'Comparație detaliată a localităților din raionul Strășeni, prezentând avantaje și dezavantaje.',
    content: 'Când cauți o casă lângă Chișinău dar nu vrei să locuiești în aglomerația orașului, raionul Strășeni oferă opțiuni excelente. Localități precum Sireți, Cojușna și Căpriana sunt foarte populare.',
    category: 'Localități',
    author: 'Andrei Moldovanu',
    date: '2026-07-10',
    readingTime: 15,
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=600&fit=crop',
    tags: ['localități', 'comparație', 'Chișinău', 'Strășeni'],
  },
  {
    id: '5',
    slug: 'teren-agricol-vs-teren-construcxii',
    title: 'Teren agricol sau teren pentru construcții? Cum alegi',
    excerpt: 'Diferențele importante și cum alegi terenul potrivit pentru necesitățile tale.',
    content: 'Una dintre deciziile importante atunci când cumperi teren este alegerea între teren agricol și teren pentru construcții. Fiecare tip are avantajele și dezavantajele sale.',
    category: 'Terenuri',
    author: 'George Vasilescu',
    date: '2026-07-05',
    readingTime: 9,
    image: 'https://images.unsplash.com/photo-1500595046743-05271c48d7d7?w=800&h=600&fit=crop',
    tags: ['teren', 'agricol', 'construcții', 'investiție'],
  },
  {
    id: '6',
    slug: 'cum-pregatesti-proprietate-vanzare',
    title: 'Cum pregătești o proprietate pentru vânzare? 10 pași',
    excerpt: 'Pași practici pentru a-ți pregăti proprietatea și a obține cel mai bun preț pe piață.',
    content: 'Atunci când vrei să vinzi o proprietate, prezentarea și starea acesteia sunt cruciale pentru a atrage cumpărători. Iată 10 pași importanți pentru a pregăti proprietatea.',
    category: 'Ghid pentru vânzători',
    author: 'Silvia Ionescu',
    date: '2026-06-30',
    readingTime: 11,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
    tags: ['vânzare', 'pregătire', 'prezentare', 'proprietate'],
  },
  {
    id: '7',
    slug: 'investitii-imobiliare-straseni-2026',
    title: 'Investiții imobiliare în Strășeni 2026 - ROI și oportunități',
    excerpt: 'Analiza piața imobiliare din Strășeni pentru investitori. Prognozele pentru 2026 și cum să profitezi de oportunități.',
    content: 'Piața imobiliară din Strășeni este în creștere continuă. Investitorii care caută randament bun ar trebui să ia în considerare Strășeni ca o destinație de investiție. Analiza amănunțită a trendurilor pieței și prognozele pentru următorii ani.',
    category: 'Investiții',
    author: 'Mihai Ionescu',
    date: '2026-08-01',
    readingTime: 14,
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    tags: ['investiții', 'ROI', 'Strășeni', 'imobiliare', '2026'],
  },
  {
    id: '8',
    slug: 'cojusna-sat-linistu-langa-chisinau',
    title: 'Cojușna - Satul linștit lângă Chișinău pentru familia ta',
    excerpt: 'Descoperă de ce Cojușna este locul perfect pentru o viață liniștită, departe de agitația capitalei dar aproape de toate facilități.',
    content: 'Cojușna este un sat frumos din raionul Strășeni, cunoscut pentru liniștea, comunitatea primească și prețurile accesibile. Doar la 50 km de Chișinău, oferă cea mai bună combinație de viață rurală și acces la oportunități urbane.',
    category: 'Localități',
    author: 'Laura Diaconu',
    date: '2026-07-25',
    readingTime: 10,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    tags: ['Cojușna', 'viață rurală', 'liniștit', 'familie'],
  },
  {
    id: '9',
    slug: 'cum-negocias-pret-proprietate-imobiliara',
    title: 'Cum negociezi prețul unei proprietăți? Strategii eficiente',
    excerpt: 'Sfaturi practice pentru a negocia cel mai bun preț atunci când cumperi o proprietate imobiliară.',
    content: 'Negocierea este o parte crucială a procesului de cumpărare a unei proprietăți. Cu strategiile corecte, poți economisi mii de euro. Iată cum să negociezi efectiv cu vânzătorul.',
    category: 'Ghid pentru cumpărători',
    author: 'Ștefan Marin',
    date: '2026-07-22',
    readingTime: 11,
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop',
    tags: ['negociere', 'preț', 'cumpărare', 'strategie'],
  },
  {
    id: '10',
    slug: 'sireti-proprietati-moderne-langa-chisinau',
    title: 'Sireți - Proprietăți moderne la doar 30 km de Chișinău',
    excerpt: 'Sireți este o localitate în dezvoltare rapidă cu proprietăți moderne și infrastructură bună. Ideal pentru cei care vor viață urbană în mediu linștit.',
    content: 'Sireți se transformă rapid în destinația preferată a investitorilor și familiilor care caută echilibru între modernitate și liniște. Aflat la doar 30 km de Chișinău, acest sat oferă acces ușor la toate facilități urbane cu prețuri mult mai accesibile.',
    category: 'Localități',
    author: 'Roxana Popescu',
    date: '2026-07-18',
    readingTime: 9,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&h=600&fit=crop',
    tags: ['Sireți', 'modern', 'Chișinău', 'proprietăți'],
  },
  {
    id: '11',
    slug: 'agentul-imobiliar-sfaturi-pentru-alegerea-celui-potrivit',
    title: 'Cum alegi agentul imobiliar potrivit? Sfaturi și întrebări',
    excerpt: 'Alegerea unui bun agent imobiliar este crucială. Iată ce ntrebări ar trebui să pui și ce caracteristici să cauti.',
    content: 'Un bun agent imobiliar vă poate economisi timp, bani și stress. Dar cum alegi agentul potrivit din mulți care oferă servicii? Iată o listă de întrebări pe care ar trebui să le pui și caracteristicile unui profesionist bun.',
    category: 'Sfaturi practice',
    author: 'Victor Andrei',
    date: '2026-07-14',
    readingTime: 8,
    image: 'https://images.unsplash.com/photo-1552085419-8ea062d8f801?w=800&h=600&fit=crop',
    tags: ['agent imobiliar', 'sfaturi', 'alegere', 'servicii'],
  },
  {
    id: '12',
    slug: 'finantare-ipoteca-moldova-ghid-complet',
    title: 'Finanțare și ipotecă în Moldova - Ghid complet 2026',
    excerpt: 'Tot ce trebuie să știi despre opțiuni de finanțare și ipoteci pentru cumpărarea unei proprietăți în Moldova.',
    content: 'Cumpărarea unei proprietăți este o decizie majoră, iar finanțarea joacă un rol crucial. În Moldova, mai sunt disponibile mai multe opțiuni de ipotecă cu condiții favorabile. Iată ghidul complet pentru a obține cea mai bună finanțare.',
    category: 'Finanțare',
    author: 'Adrian Ciobanu',
    date: '2026-07-11',
    readingTime: 13,
    image: 'https://images.unsplash.com/photo-1554224311-beee415c15c9?w=800&h=600&fit=crop',
    tags: ['finanțare', 'ipotecă', 'credite', 'Moldova'],
  },
  {
    id: '13',
    slug: 'case-in-capriana-istorie-si-natura-langa-chisinau',
    title: 'Căpriana - Case în sat istoric cu frumusețe naturală',
    excerpt: 'Căpriana este cunoscută pentru mănăstirea ei și peisajele frumoase. Descoperă de ce este destinația ideală pentru o casă.',
    content: 'Căpriana, cu mănăstirea ei slavă și peisajele spectaculoase, este o destinație unică pentru cei care vor să cumpere o casă. Situată la 50 km de Chișinău, oferă o combinație perfectă de istorie, spiritualitate și frumusețe naturală.',
    category: 'Localități',
    author: 'Cristina Vasiliu',
    date: '2026-07-08',
    readingTime: 10,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
    tags: ['Căpriana', 'istoric', 'mănăstire', 'case'],
  },
  {
    id: '14',
    slug: 'lozova-teren-agricol-pentru-fermieri',
    title: 'Lozova - Terenuri agricole fertile pentru fermieri',
    excerpt: 'Lozova este cunoscută pentru solul fertil și terenurile ideale pentru agricultură. Locul perfect pentru investitori în sector agricol.',
    content: 'Dacă ești interesat de agricultură, Lozova este destinația ta. Cu solul cel mai fertil din regiune și terenuri întinse, este locul perfect pentru a-ți dezvolta afacere agricolă. Prețuri foarte accesibile și acces bun la piețe.',
    category: 'Localități',
    author: 'Bogdan Petrescu',
    date: '2026-07-05',
    readingTime: 7,
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&h=600&fit=crop',
    tags: ['Lozova', 'agricol', 'teren', 'fermă'],
  },
  {
    id: '15',
    slug: 'vatra-viata-simpla-in-sat-langa-chisinau',
    title: 'Vatra - Viață simplă și frumoasă în sat lângă Chișinău',
    excerpt: 'Vatra este un mic sat cu tradiții puternice și comunitate unită. Descoperă cum e să locuiești într-o comunitate primească.',
    content: 'Vatra nu este doar o localitate, este o stilul de viață. Cu tradiții puternice, comunitate unită și natură frumoasă, Vatra oferă ceea ce mulți urbani caută - autenticitate și conexiune cu comunitatea.',
    category: 'Localități',
    author: 'Daniela Marinescu',
    date: '2026-07-02',
    readingTime: 8,
    image: 'https://images.unsplash.com/photo-1469022563149-aa64dbd37dae?w=800&h=600&fit=crop',
    tags: ['Vatra', 'viață tradițională', 'comunitate', 'sat'],
  },
  {
    id: '16',
    slug: 'spatii-comerciale-straseni-pentru-afaceri',
    title: 'Spații comerciale în Strășeni - Oportunități pentru afaceri',
    excerpt: 'Strășeni dezvoltă rapid sectorul comercial. Iată oportunități disponibile pentru a-ți deschide o afacere.',
    content: 'Cu dezvoltarea economică din Strășeni, spațiile comerciale devin din ce în ce mai căutate. Fie că vrei să deschizi o prăvălie, birou sau serviciu, Strășeni oferă locații strategic și prețuri competitive. Iată oportunități disponibile.',
    category: 'Comercial',
    author: 'Florin Popescu',
    date: '2026-06-28',
    readingTime: 9,
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop',
    tags: ['comercial', 'spațiu', 'afacere', 'Strășeni'],
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    title: 'Consultanță pentru cumpărare',
    description: 'Ajut pe cumpărători să găsească proprietatea potrivită și să negocieze prețul.',
  },
  {
    id: '2',
    title: 'Evaluare orientativă',
    description: 'Estimez valoarea unei proprietăți bazat pe piața locală și caracteristicile proprietății.',
  },
  {
    id: '3',
    title: 'Promovarea proprietății',
    description: 'Promovez proprietatea ta pe site-uri specializate și prin rețelele sociale.',
  },
  {
    id: '4',
    title: 'Fotografii și video',
    description: 'Realizez fotografii profesionale și videoclipuri ale proprietății tale.',
  },
  {
    id: '5',
    title: 'Redactarea anunțului',
    description: 'Pregătesc anunțuri persuasive și optimizate pentru SEO.',
  },
  {
    id: '6',
    title: 'Organizarea vizionărilor',
    description: 'Programez și organizez vizitele potențialilor cumpărători.',
  },
];
